"""add_modules_table

Revision ID: f034cfc16078
Revises: 9e67b3b2544d
Create Date: 2026-04-01 12:02:52.791292+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f034cfc16078'
down_revision: Union[str, None] = '9e67b3b2544d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_modules_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_modules_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_modules_order'), ['order'], unique=False)

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('module_id', sa.UUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_lessons_module_id'), ['module_id'], unique=False)
        batch_op.create_foreign_key(None, 'modules', ['module_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_lessons_module_id'))
        batch_op.drop_column('module_id')

    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_modules_order'))
        batch_op.drop_index(batch_op.f('ix_modules_id'))
        batch_op.drop_index(batch_op.f('ix_modules_course_id'))

    op.drop_table('modules')
    # ### end Alembic commands ###
