"""certificates

Revision ID: 9e67b3b2544d
Revises: 4181f3506288
Create Date: 2026-03-31 13:29:56.223850+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e67b3b2544d'
down_revision: Union[str, None] = '4181f3506288'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('certificate_number', sa.String(length=30), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('pdf_path', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'course_id', name='uq_certificate_user_course')
    )
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificates_certificate_number'), ['certificate_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_certificates_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificates_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificates_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificates_user_id'))
        batch_op.drop_index(batch_op.f('ix_certificates_id'))
        batch_op.drop_index(batch_op.f('ix_certificates_course_id'))
        batch_op.drop_index(batch_op.f('ix_certificates_certificate_number'))

    op.drop_table('certificates')
    # ### end Alembic commands ###
